### ISSUE TITLE
Acronyms listing

### ISSUE THREAD

**Issue by zwollo** [wfp/editorial-guide#26]
On http://cdn.wfp.org/guides/editorial/reference/wordindex/

1) The letter "H" is missing from the *Navigation*.

2) Please make the *Navigation* listing horizontal rather than vertical.

**Comment by jrah** [comment]
<img width="780" alt="screenshot 2016-05-12 11 24 10" src="https://cloud.githubusercontent.com/assets/1245961/15211705/bcf1e4f6-1834-11e6-9b47-bf48229e6cbe.png">

@zwollo How does this look for the horizontal navigation?

**Comment by zwollo** [comment]
Looks great.

**Comment by zwollo** [comment]
The "E" and "R" is also missing.

**Comment by jrah** [comment]
@zwollo englishacronyms.md was also missing "E" which I added with the above commit. I took sometime to check the others but couldn't find any other missing bookmarks that have a corresponding section. If you are happy I can leave you to close this.
