### ISSUE TITLE
acronymn navigation bar

### ISSUE THREAD

**Issue by michelleblood** [wfp/editorial-guide#27]
on http://cdn.wfp.org/guides/editorial/reference/englishacronyms/

1) Please make the Navigation listing horizontal rather than vertical.

Thanks Michelle

**Comment by jrah** [comment]
Currently [Word Index]( http://cdn.wfp.org/guides/editorial/reference/wordindex/) uses the horizontal [segmented controls](http://cdn.wfp.org/guides/ui/v0.8.0/components/navigation/#segmented-controls), however it causes the page to overflow at ~`1024x..`. 

An alternative solution would be to group the letters (A-D, E-H, etc.) and use the [Menu Inline](http://cdn.wfp.org/guides/ui/v0.8.0/components/navigation/#inline-menu) navigation component.
