### ISSUE TITLE
Add printer-friendly stylesheet

### ISSUE THREAD

**Issue by matthewmorek** [wfp/editorial-guide#6]
Editorial Guide needs a printer-friendly stylesheet to be added. @zwollo: Please, chime in with any specific requirements for this stylesheet.

**Comment by zwollo** [comment]
It needs to be paper-efficient. The guide will be printed a lot, so the less paper is wasted (narrow margins, etc.) the better.

Headers, footers and menus should not be printed. Only the core topic (body) of the page.
